/* prints a rust table of glibc's wait(2) macro results for every status word
 * 0x0000..=0xffff; build.rs captures stdout for tests/wstatus_oracle_total.rs.
 * _GNU_SOURCE must precede the includes or <sys/wait.h> leaves WCOREDUMP and
 * WIFCONTINUED undefined. */
#define _GNU_SOURCE
#include <stdio.h>
#include <sys/wait.h>

int main(void) {
    printf("// generated by oracle_probes/gen_wstatus_oracle.c; do not edit\n");
    printf("// columns: [WIFEXITED, WIFSIGNALED, WIFSTOPPED, WIFCONTINUED, WEXITSTATUS, WTERMSIG, WSTOPSIG, WCOREDUMP]\n");
    printf("pub static WSTATUS_ORACLE: [[u8; 8]; 65536] = [\n");
    for (int s = 0; s <= 0xffff; s++) {
        int st = s;
        unsigned c0 = WIFEXITED(st)    ? 1u : 0u;
        unsigned c1 = WIFSIGNALED(st)  ? 1u : 0u;
        unsigned c2 = WIFSTOPPED(st)   ? 1u : 0u;
        unsigned c3 = WIFCONTINUED(st) ? 1u : 0u;
        unsigned c4 = (unsigned)WEXITSTATUS(st) & 0xffu;
        unsigned c5 = (unsigned)WTERMSIG(st)    & 0xffu;
        unsigned c6 = (unsigned)WSTOPSIG(st)    & 0xffu;
        unsigned c7 = WCOREDUMP(st)    ? 1u : 0u;
        printf("[%u,%u,%u,%u,%u,%u,%u,%u],\n", c0, c1, c2, c3, c4, c5, c6, c7);
    }
    printf("];\n");
    return 0;
}
