// checks the linux-claiming abi constants against host glibc. the include!
// pulls PROBE_AVAILABLE plus one P_<NAME>: Option<i128> per probed macro,
// generated by build.rs from oracle_probes/uapi_const.c.
include!(concat!(env!("OUT_DIR"), "/uapi_const_glibc.rs"));

use std::mem::{align_of, offset_of, size_of};

use morpheus_foundation::flags::open_flags;
use morpheus_foundation::{errno, flags, net, syscall_abi, types};

// absent-on-host probes skip instead of silently passing a wrong value;
// probe_available hard-fails if the whole probe never ran
fn eq(found: i128, probe: Option<i128>, label: &str) {
    match probe {
        Some(v) => assert_eq!(
            found, v,
            "UAPI mismatch {label}: foundation={found} host={v}"
        ),
        None => eprintln!("SKIP {label}: host macro absent"),
    }
}

// for constants that deliberately diverge from linux
fn ne(found: i128, probe: Option<i128>, label: &str) {
    if let Some(v) = probe {
        assert_ne!(
            found, v,
            "{label} expected to DIVERGE from Linux but both == {v}"
        );
    }
}

#[test]
fn probe_available() {
    assert!(
        PROBE_AVAILABLE,
        "C uapi probe failed to compile/run on host. A C toolchain (cc/gcc) with POSIX+Linux \
         headers is required; see morpheus-foundation/build.rs stderr."
    );
}

#[test]
fn errno_matches_linux() {
    // errno is stored on-abi as -errno; errno_value() decodes to the positive int
    let cases: &[(i128, Option<i128>, &str)] = &[
        (errno::errno_value(errno::EPERM) as i128, P_EPERM, "EPERM"),
        (
            errno::errno_value(errno::ENOENT) as i128,
            P_ENOENT,
            "ENOENT",
        ),
        (errno::errno_value(errno::ESRCH) as i128, P_ESRCH, "ESRCH"),
        (errno::errno_value(errno::EINTR) as i128, P_EINTR, "EINTR"),
        (errno::errno_value(errno::EIO) as i128, P_EIO, "EIO"),
        (errno::errno_value(errno::ENXIO) as i128, P_ENXIO, "ENXIO"),
        (errno::errno_value(errno::E2BIG) as i128, P_E2BIG, "E2BIG"),
        (
            errno::errno_value(errno::ENOEXEC) as i128,
            P_ENOEXEC,
            "ENOEXEC",
        ),
        (errno::errno_value(errno::EBADF) as i128, P_EBADF, "EBADF"),
        (
            errno::errno_value(errno::ECHILD) as i128,
            P_ECHILD,
            "ECHILD",
        ),
        (
            errno::errno_value(errno::EAGAIN) as i128,
            P_EAGAIN,
            "EAGAIN",
        ),
        (
            errno::errno_value(errno::ENOMEM) as i128,
            P_ENOMEM,
            "ENOMEM",
        ),
        (
            errno::errno_value(errno::EACCES) as i128,
            P_EACCES,
            "EACCES",
        ),
        (
            errno::errno_value(errno::EFAULT) as i128,
            P_EFAULT,
            "EFAULT",
        ),
        (errno::errno_value(errno::EBUSY) as i128, P_EBUSY, "EBUSY"),
        (
            errno::errno_value(errno::EEXIST) as i128,
            P_EEXIST,
            "EEXIST",
        ),
        (errno::errno_value(errno::EXDEV) as i128, P_EXDEV, "EXDEV"),
        (
            errno::errno_value(errno::ENODEV) as i128,
            P_ENODEV,
            "ENODEV",
        ),
        (
            errno::errno_value(errno::ENOTDIR) as i128,
            P_ENOTDIR,
            "ENOTDIR",
        ),
        (
            errno::errno_value(errno::EISDIR) as i128,
            P_EISDIR,
            "EISDIR",
        ),
        (
            errno::errno_value(errno::EINVAL) as i128,
            P_EINVAL,
            "EINVAL",
        ),
        (
            errno::errno_value(errno::ENFILE) as i128,
            P_ENFILE,
            "ENFILE",
        ),
        (
            errno::errno_value(errno::EMFILE) as i128,
            P_EMFILE,
            "EMFILE",
        ),
        (
            errno::errno_value(errno::ENOTTY) as i128,
            P_ENOTTY,
            "ENOTTY",
        ),
        (
            errno::errno_value(errno::ETXTBSY) as i128,
            P_ETXTBSY,
            "ETXTBSY",
        ),
        (errno::errno_value(errno::EFBIG) as i128, P_EFBIG, "EFBIG"),
        (
            errno::errno_value(errno::ENOSPC) as i128,
            P_ENOSPC,
            "ENOSPC",
        ),
        (
            errno::errno_value(errno::ESPIPE) as i128,
            P_ESPIPE,
            "ESPIPE",
        ),
        (errno::errno_value(errno::EROFS) as i128, P_EROFS, "EROFS"),
        (
            errno::errno_value(errno::EMLINK) as i128,
            P_EMLINK,
            "EMLINK",
        ),
        (errno::errno_value(errno::EPIPE) as i128, P_EPIPE, "EPIPE"),
        (errno::errno_value(errno::EDOM) as i128, P_EDOM, "EDOM"),
        (
            errno::errno_value(errno::ERANGE) as i128,
            P_ERANGE,
            "ERANGE",
        ),
        (
            errno::errno_value(errno::EDEADLK) as i128,
            P_EDEADLK,
            "EDEADLK",
        ),
        (
            errno::errno_value(errno::ENAMETOOLONG) as i128,
            P_ENAMETOOLONG,
            "ENAMETOOLONG",
        ),
        (
            errno::errno_value(errno::ENOLCK) as i128,
            P_ENOLCK,
            "ENOLCK",
        ),
        (
            errno::errno_value(errno::ENOSYS) as i128,
            P_ENOSYS,
            "ENOSYS",
        ),
        (
            errno::errno_value(errno::ENOTEMPTY) as i128,
            P_ENOTEMPTY,
            "ENOTEMPTY",
        ),
        (errno::errno_value(errno::ELOOP) as i128, P_ELOOP, "ELOOP"),
        (
            errno::errno_value(errno::ENOMSG) as i128,
            P_ENOMSG,
            "ENOMSG",
        ),
        (
            errno::errno_value(errno::EPROTO) as i128,
            P_EPROTO,
            "EPROTO",
        ),
        (
            errno::errno_value(errno::EOVERFLOW) as i128,
            P_EOVERFLOW,
            "EOVERFLOW",
        ),
        (
            errno::errno_value(errno::ENOTSOCK) as i128,
            P_ENOTSOCK,
            "ENOTSOCK",
        ),
        (
            errno::errno_value(errno::EDESTADDRREQ) as i128,
            P_EDESTADDRREQ,
            "EDESTADDRREQ",
        ),
        (
            errno::errno_value(errno::EMSGSIZE) as i128,
            P_EMSGSIZE,
            "EMSGSIZE",
        ),
        (
            errno::errno_value(errno::EPROTOTYPE) as i128,
            P_EPROTOTYPE,
            "EPROTOTYPE",
        ),
        (
            errno::errno_value(errno::ENOPROTOOPT) as i128,
            P_ENOPROTOOPT,
            "ENOPROTOOPT",
        ),
        (
            errno::errno_value(errno::EPROTONOSUPPORT) as i128,
            P_EPROTONOSUPPORT,
            "EPROTONOSUPPORT",
        ),
        (
            errno::errno_value(errno::ESOCKTNOSUPPORT) as i128,
            P_ESOCKTNOSUPPORT,
            "ESOCKTNOSUPPORT",
        ),
        (
            errno::errno_value(errno::EOPNOTSUPP) as i128,
            P_EOPNOTSUPP,
            "EOPNOTSUPP",
        ),
        (
            errno::errno_value(errno::EPFNOSUPPORT) as i128,
            P_EPFNOSUPPORT,
            "EPFNOSUPPORT",
        ),
        (
            errno::errno_value(errno::EAFNOSUPPORT) as i128,
            P_EAFNOSUPPORT,
            "EAFNOSUPPORT",
        ),
        (
            errno::errno_value(errno::EADDRINUSE) as i128,
            P_EADDRINUSE,
            "EADDRINUSE",
        ),
        (
            errno::errno_value(errno::EADDRNOTAVAIL) as i128,
            P_EADDRNOTAVAIL,
            "EADDRNOTAVAIL",
        ),
        (
            errno::errno_value(errno::ENETDOWN) as i128,
            P_ENETDOWN,
            "ENETDOWN",
        ),
        (
            errno::errno_value(errno::ENETUNREACH) as i128,
            P_ENETUNREACH,
            "ENETUNREACH",
        ),
        (
            errno::errno_value(errno::ENETRESET) as i128,
            P_ENETRESET,
            "ENETRESET",
        ),
        (
            errno::errno_value(errno::ECONNABORTED) as i128,
            P_ECONNABORTED,
            "ECONNABORTED",
        ),
        (
            errno::errno_value(errno::ECONNRESET) as i128,
            P_ECONNRESET,
            "ECONNRESET",
        ),
        (
            errno::errno_value(errno::ENOBUFS) as i128,
            P_ENOBUFS,
            "ENOBUFS",
        ),
        (
            errno::errno_value(errno::EISCONN) as i128,
            P_EISCONN,
            "EISCONN",
        ),
        (
            errno::errno_value(errno::ENOTCONN) as i128,
            P_ENOTCONN,
            "ENOTCONN",
        ),
        (
            errno::errno_value(errno::ESHUTDOWN) as i128,
            P_ESHUTDOWN,
            "ESHUTDOWN",
        ),
        (
            errno::errno_value(errno::ETIMEDOUT) as i128,
            P_ETIMEDOUT,
            "ETIMEDOUT",
        ),
        (
            errno::errno_value(errno::ECONNREFUSED) as i128,
            P_ECONNREFUSED,
            "ECONNREFUSED",
        ),
        (
            errno::errno_value(errno::EHOSTDOWN) as i128,
            P_EHOSTDOWN,
            "EHOSTDOWN",
        ),
        (
            errno::errno_value(errno::EHOSTUNREACH) as i128,
            P_EHOSTUNREACH,
            "EHOSTUNREACH",
        ),
        (
            errno::errno_value(errno::EALREADY) as i128,
            P_EALREADY,
            "EALREADY",
        ),
        (
            errno::errno_value(errno::EINPROGRESS) as i128,
            P_EINPROGRESS,
            "EINPROGRESS",
        ),
        (
            errno::errno_value(errno::ESTALE) as i128,
            P_ESTALE,
            "ESTALE",
        ),
        (
            errno::errno_value(errno::EDQUOT) as i128,
            P_EDQUOT,
            "EDQUOT",
        ),
        (
            errno::errno_value(errno::ECANCELED) as i128,
            P_ECANCELED,
            "ECANCELED",
        ),
    ];
    for &(f, p, l) in cases {
        eq(f, p, l);
    }
    // linux aliases: EWOULDBLOCK == EAGAIN, ENOTSUP == EOPNOTSUPP
    assert_eq!(
        errno::EWOULDBLOCK,
        errno::EAGAIN,
        "EWOULDBLOCK must alias EAGAIN"
    );
    assert_eq!(
        errno::ENOTSUP,
        errno::EOPNOTSUPP,
        "ENOTSUP must alias EOPNOTSUPP"
    );
}

#[test]
fn flags_match_linux() {
    let cases: &[(i128, Option<i128>, &str)] = &[
        (open_flags::O_NONBLOCK as i128, P_O_NONBLOCK, "O_NONBLOCK"),
        (open_flags::O_CLOEXEC as i128, P_O_CLOEXEC, "O_CLOEXEC"),
        (flags::mode::S_IFMT as i128, P_S_IFMT, "S_IFMT"),
        (flags::mode::S_IFSOCK as i128, P_S_IFSOCK, "S_IFSOCK"),
        (flags::mode::S_IFLNK as i128, P_S_IFLNK, "S_IFLNK"),
        (flags::mode::S_IFREG as i128, P_S_IFREG, "S_IFREG"),
        (flags::mode::S_IFBLK as i128, P_S_IFBLK, "S_IFBLK"),
        (flags::mode::S_IFDIR as i128, P_S_IFDIR, "S_IFDIR"),
        (flags::mode::S_IFCHR as i128, P_S_IFCHR, "S_IFCHR"),
        (flags::mode::S_IFIFO as i128, P_S_IFIFO, "S_IFIFO"),
        (
            flags::dirent_type::DT_UNKNOWN as i128,
            P_DT_UNKNOWN,
            "DT_UNKNOWN",
        ),
        (flags::dirent_type::DT_FIFO as i128, P_DT_FIFO, "DT_FIFO"),
        (flags::dirent_type::DT_CHR as i128, P_DT_CHR, "DT_CHR"),
        (flags::dirent_type::DT_DIR as i128, P_DT_DIR, "DT_DIR"),
        (flags::dirent_type::DT_BLK as i128, P_DT_BLK, "DT_BLK"),
        (flags::dirent_type::DT_REG as i128, P_DT_REG, "DT_REG"),
        (flags::dirent_type::DT_LNK as i128, P_DT_LNK, "DT_LNK"),
        (flags::dirent_type::DT_SOCK as i128, P_DT_SOCK, "DT_SOCK"),
        (
            flags::CLOCK_REALTIME as i128,
            P_CLOCK_REALTIME,
            "CLOCK_REALTIME",
        ),
        (
            flags::CLOCK_MONOTONIC as i128,
            P_CLOCK_MONOTONIC,
            "CLOCK_MONOTONIC",
        ),
        (flags::WNOHANG as i128, P_WNOHANG, "WNOHANG"),
        (flags::WUNTRACED as i128, P_WUNTRACED, "WUNTRACED"),
        (flags::WCONTINUED as i128, P_WCONTINUED, "WCONTINUED"),
        (flags::F_DUPFD as i128, P_F_DUPFD, "F_DUPFD"),
        (flags::F_GETFD as i128, P_F_GETFD, "F_GETFD"),
        (flags::F_SETFD as i128, P_F_SETFD, "F_SETFD"),
        (flags::F_GETFL as i128, P_F_GETFL, "F_GETFL"),
        (flags::F_SETFL as i128, P_F_SETFL, "F_SETFL"),
        (
            flags::F_DUPFD_CLOEXEC as i128,
            P_F_DUPFD_CLOEXEC,
            "F_DUPFD_CLOEXEC",
        ),
        (flags::FD_CLOEXEC as i128, P_FD_CLOEXEC, "FD_CLOEXEC"),
        (
            flags::EPOLL_CLOEXEC as i128,
            P_EPOLL_CLOEXEC,
            "EPOLL_CLOEXEC",
        ),
        (
            flags::EPOLL_CTL_ADD as i128,
            P_EPOLL_CTL_ADD,
            "EPOLL_CTL_ADD",
        ),
        (
            flags::EPOLL_CTL_DEL as i128,
            P_EPOLL_CTL_DEL,
            "EPOLL_CTL_DEL",
        ),
        (
            flags::EPOLL_CTL_MOD as i128,
            P_EPOLL_CTL_MOD,
            "EPOLL_CTL_MOD",
        ),
        (flags::EPOLLIN as i128, P_EPOLLIN, "EPOLLIN"),
        (flags::EPOLLPRI as i128, P_EPOLLPRI, "EPOLLPRI"),
        (flags::EPOLLOUT as i128, P_EPOLLOUT, "EPOLLOUT"),
        (flags::EPOLLERR as i128, P_EPOLLERR, "EPOLLERR"),
        (flags::EPOLLHUP as i128, P_EPOLLHUP, "EPOLLHUP"),
        (flags::EPOLLRDHUP as i128, P_EPOLLRDHUP, "EPOLLRDHUP"),
        (flags::EPOLLONESHOT as i128, P_EPOLLONESHOT, "EPOLLONESHOT"),
        (flags::EPOLLET as i128, P_EPOLLET, "EPOLLET"),
        (
            flags::AT_SYMLINK_NOFOLLOW as i128,
            P_AT_SYMLINK_NOFOLLOW,
            "AT_SYMLINK_NOFOLLOW",
        ),
        (flags::MAP_SHARED as i128, P_MAP_SHARED, "MAP_SHARED"),
        (flags::MAP_PRIVATE as i128, P_MAP_PRIVATE, "MAP_PRIVATE"),
        (flags::MAP_FIXED as i128, P_MAP_FIXED, "MAP_FIXED"),
        (
            flags::MAP_ANONYMOUS as i128,
            P_MAP_ANONYMOUS,
            "MAP_ANONYMOUS",
        ),
        (flags::FUTEX_WAIT as i128, P_FUTEX_WAIT, "FUTEX_WAIT"),
        (flags::FUTEX_WAKE as i128, P_FUTEX_WAKE, "FUTEX_WAKE"),
        (
            flags::FUTEX_WAIT_BITSET as i128,
            P_FUTEX_WAIT_BITSET,
            "FUTEX_WAIT_BITSET",
        ),
        (
            flags::FUTEX_WAKE_BITSET as i128,
            P_FUTEX_WAKE_BITSET,
            "FUTEX_WAKE_BITSET",
        ),
        (flags::IOCTL_FIONREAD as i128, P_FIONREAD, "IOCTL_FIONREAD"),
        (flags::IOCTL_FIONBIO as i128, P_FIONBIO, "IOCTL_FIONBIO"),
        (
            flags::IOCTL_TIOCGWINSZ as i128,
            P_TIOCGWINSZ,
            "IOCTL_TIOCGWINSZ",
        ),
        (flags::POLLIN as i128, P_POLLIN, "POLLIN"),
        (flags::POLLPRI as i128, P_POLLPRI, "POLLPRI"),
        (flags::POLLOUT as i128, P_POLLOUT, "POLLOUT"),
        (flags::POLLERR as i128, P_POLLERR, "POLLERR"),
        (flags::POLLHUP as i128, P_POLLHUP, "POLLHUP"),
        (flags::POLLNVAL as i128, P_POLLNVAL, "POLLNVAL"),
        (flags::POLLRDHUP as i128, P_POLLRDHUP, "POLLRDHUP"),
        (flags::signal::SIGINT as i128, P_SIGINT, "SIGINT"),
        (flags::signal::SIGKILL as i128, P_SIGKILL, "SIGKILL"),
        (flags::signal::SIGSEGV as i128, P_SIGSEGV, "SIGSEGV"),
        (flags::signal::SIGTERM as i128, P_SIGTERM, "SIGTERM"),
        (flags::signal::SIGCHLD as i128, P_SIGCHLD, "SIGCHLD"),
        (flags::signal::SIGCONT as i128, P_SIGCONT, "SIGCONT"),
        (flags::signal::SIGSTOP as i128, P_SIGSTOP, "SIGSTOP"),
    ];
    for &(f, p, l) in cases {
        eq(f, p, l);
    }
}

#[test]
fn net_match_linux() {
    let cases: &[(i128, Option<i128>, &str)] = &[
        (net::AF_UNSPEC as i128, P_AF_UNSPEC, "AF_UNSPEC"),
        (net::AF_INET as i128, P_AF_INET, "AF_INET"),
        (net::AF_INET6 as i128, P_AF_INET6, "AF_INET6"),
        (net::SOCK_STREAM as i128, P_SOCK_STREAM, "SOCK_STREAM"),
        (net::SOCK_DGRAM as i128, P_SOCK_DGRAM, "SOCK_DGRAM"),
        (net::SOCK_NONBLOCK as i128, P_SOCK_NONBLOCK, "SOCK_NONBLOCK"),
        (net::SOCK_CLOEXEC as i128, P_SOCK_CLOEXEC, "SOCK_CLOEXEC"),
        (net::IPPROTO_IP as i128, P_IPPROTO_IP, "IPPROTO_IP"),
        (net::IPPROTO_TCP as i128, P_IPPROTO_TCP, "IPPROTO_TCP"),
        (net::IPPROTO_UDP as i128, P_IPPROTO_UDP, "IPPROTO_UDP"),
        (net::IPPROTO_IPV6 as i128, P_IPPROTO_IPV6, "IPPROTO_IPV6"),
        (net::SOL_SOCKET as i128, P_SOL_SOCKET, "SOL_SOCKET"),
        (net::SO_REUSEADDR as i128, P_SO_REUSEADDR, "SO_REUSEADDR"),
        (net::SO_ERROR as i128, P_SO_ERROR, "SO_ERROR"),
        (net::SO_BROADCAST as i128, P_SO_BROADCAST, "SO_BROADCAST"),
        (net::SO_SNDBUF as i128, P_SO_SNDBUF, "SO_SNDBUF"),
        (net::SO_RCVBUF as i128, P_SO_RCVBUF, "SO_RCVBUF"),
        (net::SO_KEEPALIVE as i128, P_SO_KEEPALIVE, "SO_KEEPALIVE"),
        (net::SO_LINGER as i128, P_SO_LINGER, "SO_LINGER"),
        (net::SO_REUSEPORT as i128, P_SO_REUSEPORT, "SO_REUSEPORT"),
        (net::SO_RCVTIMEO as i128, P_SO_RCVTIMEO, "SO_RCVTIMEO"),
        (net::SO_SNDTIMEO as i128, P_SO_SNDTIMEO, "SO_SNDTIMEO"),
        (net::TCP_NODELAY as i128, P_TCP_NODELAY, "TCP_NODELAY"),
        (net::TCP_KEEPIDLE as i128, P_TCP_KEEPIDLE, "TCP_KEEPIDLE"),
        (net::TCP_KEEPINTVL as i128, P_TCP_KEEPINTVL, "TCP_KEEPINTVL"),
        (net::TCP_KEEPCNT as i128, P_TCP_KEEPCNT, "TCP_KEEPCNT"),
        (net::IP_TTL as i128, P_IP_TTL, "IP_TTL"),
        (
            net::IP_MULTICAST_TTL as i128,
            P_IP_MULTICAST_TTL,
            "IP_MULTICAST_TTL",
        ),
        (
            net::IP_MULTICAST_LOOP as i128,
            P_IP_MULTICAST_LOOP,
            "IP_MULTICAST_LOOP",
        ),
        (
            net::IP_ADD_MEMBERSHIP as i128,
            P_IP_ADD_MEMBERSHIP,
            "IP_ADD_MEMBERSHIP",
        ),
        (
            net::IP_DROP_MEMBERSHIP as i128,
            P_IP_DROP_MEMBERSHIP,
            "IP_DROP_MEMBERSHIP",
        ),
        (
            net::IPV6_MULTICAST_LOOP as i128,
            P_IPV6_MULTICAST_LOOP,
            "IPV6_MULTICAST_LOOP",
        ),
        (
            net::IPV6_ADD_MEMBERSHIP as i128,
            P_IPV6_ADD_MEMBERSHIP,
            "IPV6_ADD_MEMBERSHIP",
        ),
        (
            net::IPV6_DROP_MEMBERSHIP as i128,
            P_IPV6_DROP_MEMBERSHIP,
            "IPV6_DROP_MEMBERSHIP",
        ),
        (net::IPV6_V6ONLY as i128, P_IPV6_V6ONLY, "IPV6_V6ONLY"),
        (net::SHUT_RD as i128, P_SHUT_RD, "SHUT_RD"),
        (net::SHUT_WR as i128, P_SHUT_WR, "SHUT_WR"),
        (net::SHUT_RDWR as i128, P_SHUT_RDWR, "SHUT_RDWR"),
        (net::MSG_PEEK as i128, P_MSG_PEEK, "MSG_PEEK"),
        (net::MSG_DONTWAIT as i128, P_MSG_DONTWAIT, "MSG_DONTWAIT"),
        (net::MSG_NOSIGNAL as i128, P_MSG_NOSIGNAL, "MSG_NOSIGNAL"),
    ];
    for &(f, p, l) in cases {
        eq(f, p, l);
    }
}

#[test]
fn seek_and_grnd_match_linux() {
    let cases: &[(i128, Option<i128>, &str)] = &[
        (syscall_abi::SEEK_SET as i128, P_SEEK_SET, "SEEK_SET"),
        (syscall_abi::SEEK_CUR as i128, P_SEEK_CUR, "SEEK_CUR"),
        (syscall_abi::SEEK_END as i128, P_SEEK_END, "SEEK_END"),
        (
            syscall_abi::GRND_NONBLOCK as i128,
            P_GRND_NONBLOCK,
            "GRND_NONBLOCK",
        ),
    ];
    for &(f, p, l) in cases {
        eq(f, p, l);
    }
}

#[test]
fn intentional_divergences() {
    // mmap prot: foundation uses read-implicit 0/1/2 + guard bit 4, not linux
    // 1/2/4 with PROT_NONE=0; pin the documented values and assert divergence
    assert_eq!(flags::PROT_READ, 0, "PROT_READ documented value");
    assert_eq!(flags::PROT_WRITE, 1, "PROT_WRITE documented value");
    assert_eq!(flags::PROT_EXEC, 2, "PROT_EXEC documented value");
    assert_eq!(flags::PROT_NONE, 0x4, "PROT_NONE documented value");
    ne(flags::PROT_READ as i128, P_PROT_READ, "PROT_READ");
    ne(flags::PROT_WRITE as i128, P_PROT_WRITE, "PROT_WRITE");
    ne(flags::PROT_EXEC as i128, P_PROT_EXEC, "PROT_EXEC");
    ne(flags::PROT_NONE as i128, P_PROT_NONE, "PROT_NONE");
    // flat O_* bitmask: morpheusx's own bits, not linux O_*
    assert_eq!(open_flags::O_READ, 0x01, "O_READ documented value");
    assert_eq!(open_flags::O_WRITE, 0x02, "O_WRITE documented value");
    assert_eq!(open_flags::O_CREATE, 0x04, "O_CREATE documented value");
    assert_eq!(open_flags::O_EXCL, 0x08, "O_EXCL documented value");
    assert_eq!(open_flags::O_TRUNC, 0x10, "O_TRUNC documented value");
    assert_eq!(open_flags::O_APPEND, 0x20, "O_APPEND documented value");
    ne(
        open_flags::O_CREATE as i128,
        P_O_CREAT,
        "O_CREATE vs Linux O_CREAT",
    );
    ne(
        open_flags::O_EXCL as i128,
        P_O_EXCL,
        "O_EXCL vs Linux O_EXCL",
    );
    ne(
        open_flags::O_TRUNC as i128,
        P_O_TRUNC,
        "O_TRUNC vs Linux O_TRUNC",
    );
    ne(
        open_flags::O_APPEND as i128,
        P_O_APPEND,
        "O_APPEND vs Linux O_APPEND",
    );
}

#[test]
fn struct_layout_matches_libc() {
    // sockaddr_in
    assert_eq!(
        size_of::<types::SockAddrIn>(),
        size_of::<libc::sockaddr_in>(),
        "SockAddrIn size"
    );
    assert_eq!(
        offset_of!(types::SockAddrIn, sin_family),
        offset_of!(libc::sockaddr_in, sin_family)
    );
    assert_eq!(
        offset_of!(types::SockAddrIn, sin_port),
        offset_of!(libc::sockaddr_in, sin_port)
    );
    assert_eq!(
        offset_of!(types::SockAddrIn, sin_addr),
        offset_of!(libc::sockaddr_in, sin_addr)
    );
    assert_eq!(
        offset_of!(types::SockAddrIn, sin_zero),
        offset_of!(libc::sockaddr_in, sin_zero)
    );
    // pollfd
    assert_eq!(
        size_of::<types::PollFd>(),
        size_of::<libc::pollfd>(),
        "PollFd size"
    );
    assert_eq!(offset_of!(types::PollFd, fd), offset_of!(libc::pollfd, fd));
    assert_eq!(
        offset_of!(types::PollFd, events),
        offset_of!(libc::pollfd, events)
    );
    assert_eq!(
        offset_of!(types::PollFd, revents),
        offset_of!(libc::pollfd, revents)
    );
    // timespec
    assert_eq!(
        size_of::<types::Timespec>(),
        size_of::<libc::timespec>(),
        "Timespec size"
    );
    assert_eq!(
        offset_of!(types::Timespec, tv_sec),
        offset_of!(libc::timespec, tv_sec)
    );
    assert_eq!(
        offset_of!(types::Timespec, tv_nsec),
        offset_of!(libc::timespec, tv_nsec)
    );
    // timeval / KTimeval
    assert_eq!(
        size_of::<types::KTimeval>(),
        size_of::<libc::timeval>(),
        "KTimeval size"
    );
    assert_eq!(
        offset_of!(types::KTimeval, tv_sec),
        offset_of!(libc::timeval, tv_sec)
    );
    assert_eq!(
        offset_of!(types::KTimeval, tv_usec),
        offset_of!(libc::timeval, tv_usec)
    );
    // linger
    assert_eq!(
        size_of::<types::Linger>(),
        size_of::<libc::linger>(),
        "Linger size"
    );
    assert_eq!(
        offset_of!(types::Linger, l_onoff),
        offset_of!(libc::linger, l_onoff)
    );
    assert_eq!(
        offset_of!(types::Linger, l_linger),
        offset_of!(libc::linger, l_linger)
    );
    // ip_mreq
    assert_eq!(
        size_of::<types::IpMreq>(),
        size_of::<libc::ip_mreq>(),
        "IpMreq size"
    );
    assert_eq!(
        offset_of!(types::IpMreq, imr_multiaddr),
        offset_of!(libc::ip_mreq, imr_multiaddr)
    );
    assert_eq!(
        offset_of!(types::IpMreq, imr_interface),
        offset_of!(libc::ip_mreq, imr_interface)
    );
    // ipv6_mreq
    assert_eq!(
        size_of::<types::Ipv6Mreq>(),
        size_of::<libc::ipv6_mreq>(),
        "Ipv6Mreq size"
    );
    assert_eq!(
        offset_of!(types::Ipv6Mreq, ipv6mr_multiaddr),
        offset_of!(libc::ipv6_mreq, ipv6mr_multiaddr)
    );
    assert_eq!(
        offset_of!(types::Ipv6Mreq, ipv6mr_interface),
        offset_of!(libc::ipv6_mreq, ipv6mr_interface)
    );
    // EpollEvent is deliberately 16b natural-aligned, not libc's 12b packed
    // epoll_event; pin its documented shape and assert the divergence
    assert_eq!(
        size_of::<types::EpollEvent>(),
        16,
        "EpollEvent must stay 16B"
    );
    assert_eq!(align_of::<types::EpollEvent>(), 8, "EpollEvent align");
    assert_eq!(
        offset_of!(types::EpollEvent, data),
        8,
        "EpollEvent.data offset"
    );
    assert_ne!(
        size_of::<types::EpollEvent>(),
        size_of::<libc::epoll_event>(),
        "EpollEvent divergence intended: foundation 16B vs libc packed 12B"
    );
}
