#!/bin/bash
# Extract .reloc section data and generate embedded_reloc_data.rs
# Run this AFTER building the bootloader: cargo build --target x86_64-unknown-uefi --release

set -e

EFI_FILE="${1:-target/x86_64-unknown-uefi/release/morpheus-bootloader.efi}"
OUTPUT_FILE="persistent/src/pe/embedded_reloc_data.rs"

if [ ! -f "$EFI_FILE" ]; then
    echo "Error: EFI file not found: $EFI_FILE"
    echo "Usage: $0 [path-to-efi-file]"
    exit 1
fi

echo "Extracting relocation data from: $EFI_FILE"

# Read e_lfanew (PE header offset)
E_LFANEW=$(od -An -t x4 -j 0x3C -N 4 "$EFI_FILE" | tr -d ' ' | sed 's/^/0x/')
E_LFANEW_DEC=$((E_LFANEW))

echo "PE header at offset: $E_LFANEW"

# Read number of sections
SECTION_COUNT_OFFSET=$((E_LFANEW_DEC + 6))
SECTION_COUNT=$(od -An -t u2 -j "$SECTION_COUNT_OFFSET" -N 2 "$EFI_FILE" | tr -d ' ')

echo "Number of sections: $SECTION_COUNT"

# Read optional header size
OPT_HEADER_SIZE_OFFSET=$((E_LFANEW_DEC + 20))
OPT_HEADER_SIZE=$(od -An -t u2 -j "$OPT_HEADER_SIZE_OFFSET" -N 2 "$EFI_FILE" | tr -d ' ')

# Section table starts after: PE sig (4) + COFF header (20) + optional header
SECTION_TABLE_OFFSET=$((E_LFANEW_DEC + 24 + OPT_HEADER_SIZE))

echo "Section table at offset: 0x$(printf '%X' $SECTION_TABLE_OFFSET)"

# Find .reloc section
RELOC_RVA=""
RELOC_VSIZE=""
RELOC_FOFFSET=""
RELOC_FSIZE=""

for ((i=0; i<SECTION_COUNT; i++)); do
    SEC_OFFSET=$((SECTION_TABLE_OFFSET + i * 40))
    
    # Read section name (8 bytes)
    SEC_NAME=$(dd if="$EFI_FILE" bs=1 skip=$SEC_OFFSET count=8 2>/dev/null | tr -d '\0')
    
    if [ "$SEC_NAME" = ".reloc" ]; then
        # Virtual size (offset +8)
        RELOC_VSIZE=$(od -An -t x4 -j $((SEC_OFFSET + 8)) -N 4 "$EFI_FILE" | tr -d ' ' | sed 's/^/0x/')
        # Virtual address / RVA (offset +12)
        RELOC_RVA=$(od -An -t x4 -j $((SEC_OFFSET + 12)) -N 4 "$EFI_FILE" | tr -d ' ' | sed 's/^/0x/')
        # Size of raw data (offset +16)
        RELOC_FSIZE=$(od -An -t x4 -j $((SEC_OFFSET + 16)) -N 4 "$EFI_FILE" | tr -d ' ' | sed 's/^/0x/')
        # Pointer to raw data (offset +20)
        RELOC_FOFFSET=$(od -An -t x4 -j $((SEC_OFFSET + 20)) -N 4 "$EFI_FILE" | tr -d ' ' | sed 's/^/0x/')
        break
    fi
done

if [ -z "$RELOC_RVA" ]; then
    echo "Error: .reloc section not found!"
    exit 1
fi

echo "Found .reloc section:"
echo "  RVA: $RELOC_RVA"
echo "  Virtual Size: $RELOC_VSIZE"
echo "  File Offset: $RELOC_FOFFSET"
echo "  File Size: $RELOC_FSIZE"

# Extract ImageBase
IMAGE_BASE_OFFSET=$((E_LFANEW_DEC + 24 + 24))
IMAGE_BASE_RAW=$(od -An -t x8 -j "$IMAGE_BASE_OFFSET" -N 8 "$EFI_FILE" | tr -d ' ')

# Convert little-endian to proper hex
B1=${IMAGE_BASE_RAW:14:2}
B2=${IMAGE_BASE_RAW:12:2}
B3=${IMAGE_BASE_RAW:10:2}
B4=${IMAGE_BASE_RAW:8:2}
B5=${IMAGE_BASE_RAW:6:2}
B6=${IMAGE_BASE_RAW:4:2}
B7=${IMAGE_BASE_RAW:2:2}
B8=${IMAGE_BASE_RAW:0:2}
IMAGE_BASE="0x${B1}${B2}${B3}${B4}${B5}${B6}${B7}${B8}"

echo "  ImageBase: $IMAGE_BASE"

# Extract reloc data - use VirtualSize (actual data) not RawSize (padded)
RELOC_SIZE_DEC=$((RELOC_VSIZE))
RELOC_OFFSET_DEC=$((RELOC_FOFFSET))

# Generate Rust source file
cat > "$OUTPUT_FILE" << 'EOF'
//! Hardcoded relocation data
//! 
//! UEFI discards .reloc section from memory after applying relocations.
//! This data is the original .reloc section content, embedded in the code
//! so it's always available for unrelocating the image.
//!
//! AUTO-GENERATED by tools/extract-reloc-data.sh
//! Run: ./tools/extract-reloc-data.sh after each build

EOF

# Add constants
echo "/// Original .reloc section RVA" >> "$OUTPUT_FILE"
echo "pub const RELOC_RVA: u32 = $RELOC_RVA;" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo "/// Original .reloc section size" >> "$OUTPUT_FILE"  
echo "pub const RELOC_SIZE: u32 = $RELOC_VSIZE;" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo "/// Original ImageBase from linker script" >> "$OUTPUT_FILE"
echo "pub const ORIGINAL_IMAGE_BASE: u64 = $IMAGE_BASE;" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Extract and format reloc data
echo "/// Hardcoded .reloc section data ($RELOC_SIZE_DEC bytes)" >> "$OUTPUT_FILE"
echo "/// Extracted from morpheus-bootloader.efi at file offset $RELOC_FOFFSET" >> "$OUTPUT_FILE"
echo "#[allow(dead_code)]" >> "$OUTPUT_FILE"
echo "pub const RELOC_DATA: [u8; $RELOC_SIZE_DEC] = [" >> "$OUTPUT_FILE"

# Extract bytes and format as Rust array  
python3 << PYTHON
with open("$EFI_FILE", "rb") as f:
    f.seek($RELOC_OFFSET_DEC)
    data = f.read($RELOC_SIZE_DEC)
    
with open("$OUTPUT_FILE", "a") as out:
    out.write("    ")
    for i, byte in enumerate(data):
        out.write(f"0x{byte:02x}, ")
        if (i + 1) % 12 == 0 and i < len(data) - 1:
            out.write("\n    ")
    out.write("\n")
PYTHON

echo "" >> "$OUTPUT_FILE"
echo "];" >> "$OUTPUT_FILE"

echo ""
echo "Successfully generated: $OUTPUT_FILE"
echo ""
echo "IMPORTANT: Rebuild the project after this!"
echo "  cargo build --target x86_64-unknown-uefi --release"
